// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	payment "pinjamtani_project/internal/features/payments"

	mock "github.com/stretchr/testify/mock"
)

// QueryPaymentInterface is an autogenerated mock type for the QueryPaymentInterface type
type QueryPaymentInterface struct {
	mock.Mock
}

// UpdateStatusOrder provides a mock function with given fields: dataUserMidtrans
func (_m *QueryPaymentInterface) UpdateStatusOrder(dataUserMidtrans payment.MidtransRequestEntity) error {
	ret := _m.Called(dataUserMidtrans)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(payment.MidtransRequestEntity) error); ok {
		r0 = rf(dataUserMidtrans)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueryPaymentInterface creates a new instance of QueryPaymentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryPaymentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryPaymentInterface {
	mock := &QueryPaymentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
