// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	products "pinjamtani_project/internal/features/products"

	mock "github.com/stretchr/testify/mock"
)

// ServiceProductInterface is an autogenerated mock type for the ServiceProductInterface type
type ServiceProductInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: product
func (_m *ServiceProductInterface) Create(product products.ProductsEntity) (uint, error) {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(products.ProductsEntity) (uint, error)); ok {
		return rf(product)
	}
	if rf, ok := ret.Get(0).(func(products.ProductsEntity) uint); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(products.ProductsEntity) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id, userid
func (_m *ServiceProductInterface) Delete(id uint, userid uint) error {
	ret := _m.Called(id, userid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(id, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllProduct provides a mock function with given fields: productName, page, pageSize
func (_m *ServiceProductInterface) GetAllProduct(productName string, page int, pageSize int) ([]products.ProductsEntity, error) {
	ret := _m.Called(productName, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProduct")
	}

	var r0 []products.ProductsEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]products.ProductsEntity, error)); ok {
		return rf(productName, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []products.ProductsEntity); ok {
		r0 = rf(productName, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]products.ProductsEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(productName, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *ServiceProductInterface) GetById(id uint) (*products.ProductsEntity, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *products.ProductsEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*products.ProductsEntity, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *products.ProductsEntity); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*products.ProductsEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProducts provides a mock function with given fields: userID, page, pageSize
func (_m *ServiceProductInterface) GetUserProducts(userID uint, page int, pageSize int) ([]products.ProductsEntity, error) {
	ret := _m.Called(userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProducts")
	}

	var r0 []products.ProductsEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]products.ProductsEntity, error)); ok {
		return rf(userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []products.ProductsEntity); ok {
		r0 = rf(userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]products.ProductsEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(userID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, userid, product
func (_m *ServiceProductInterface) Update(id uint, userid uint, product products.ProductsEntity) error {
	ret := _m.Called(id, userid, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, products.ProductsEntity) error); ok {
		r0 = rf(id, userid, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceProductInterface creates a new instance of ServiceProductInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProductInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProductInterface {
	mock := &ServiceProductInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
