// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	payment "pinjamtani_project/internal/features/payments"

	mock "github.com/stretchr/testify/mock"
)

// ServicePaymentIinterface is an autogenerated mock type for the ServicePaymentIinterface type
type ServicePaymentIinterface struct {
	mock.Mock
}

// UpdatePaymentStatus provides a mock function with given fields: reqMidtrans
func (_m *ServicePaymentIinterface) UpdatePaymentStatus(reqMidtrans payment.MidtransRequestEntity) error {
	ret := _m.Called(reqMidtrans)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(payment.MidtransRequestEntity) error); ok {
		r0 = rf(reqMidtrans)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServicePaymentIinterface creates a new instance of ServicePaymentIinterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicePaymentIinterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicePaymentIinterface {
	mock := &ServicePaymentIinterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
